[server]
# O nome que aparecerá na rede (argus-pump.local)
host-name=argus-pump
use-ipv4=yes
use-ipv6=no
allow-interfaces=wlan0

[publish]
publish-addresses=yes
publish-hinfo=yes
publish-workstation=no
publish-domain=yes

[reflector]
enable-reflector=no
reflect-ipv=no

[rlimits]
