# Controle de Versao Centralizado
ARGUS_VERSION_MAJOR = "1"
ARGUS_VERSION_MINOR = "0"
ARGUS_VERSION_PATCH = "9"

# String completa (Ex: 1.0.1)
ARGUS_VERSION_STRING = "${ARGUS_VERSION_MAJOR}.${ARGUS_VERSION_MINOR}.${ARGUS_VERSION_PATCH}"
