# --- GERAL ---
user root
pid_file /var/run/mosquitto.pid
persistence true
persistence_location /var/lib/mosquitto/

# --- SEGURANÇA & LOGS ---
#log_dest syslog
log_dest stdout
log_type error
log_type warning
log_type notice
# Habilita ACL
acl_file /etc/mosquitto/acl

# -----------------------------------------------------------------
# LISTENER 1: LOCALHOST (Interno - Sem Criptografia)
# -----------------------------------------------------------------
# O Boost Asio e o Gateway interno usam essa porta.
# Bind apenas em 127.0.0.1 impede acesso externo.
listener 1883 127.0.0.1
allow_anonymous true

# -----------------------------------------------------------------
# LISTENER 2: EXTERNO (Backend - TLS + mTLS)
# -----------------------------------------------------------------
listener 8883 0.0.0.0

# Certificados do Servidor
cafile /etc/mosquitto/certs/ca.crt
certfile /etc/mosquitto/certs/server.crt
keyfile /etc/mosquitto/certs/server.key

# EXIGIR Autenticação Mútua (mTLS)
# O cliente OBRIGATORIAMENTE precisa apresentar um certificado válido
require_certificate true

# ACL baseada em Identidade
# Usa o CN do certificado (ex: "backend-service") como username para o ACL
use_identity_as_username true
